apiVersion: apps/v1
kind: Deployment
metadata:
  # Deployment의 이름
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      # 템플릿에서 사용할 컨테이너 스펙
      containers:
      - name: nginx
        image: nginx