apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: daein-logstash
  name: daein-logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: daein-logstash
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/elastic: "true"
        io.kompose.service: daein-logstash
    spec:
      containers:
        - image: dnfwlxo11/daein-lyrics-logstash:1.2.0
          name: daein-logstash
          ports:
            - containerPort: 5001
          resources: {}
          volumeMounts:
            - mountPath: /usr/share/logstash/config/logstash.yml
              name: daein-logstash-claim0
            - mountPath: /usr/share/logstash/pipeline/logstash.conf
              name: daein-logstash-claim1
            - mountPath: /opt/logstash/vendor/jar/jdbc/mariadb-java-client-2.7.5.jar
              name: daein-logstash-claim2
      restartPolicy: Always
      volumes:
        - name: daein-logstash-claim0
          hostPath:
            path: volumes/logstash/config
        - name: daein-logstash-claim1
          hostPath:
            path: volumes/logstash/config
        - name: daein-logstash-claim2
          hostPath:
            path: volumes/logstash/drive
status: {}
