apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: daein-logstash
  name: daein-logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: daein-logstash
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --volumes hostPath
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/elastic: "true"
        io.kompose.service: daein-logstash
    spec:
      containers:
        - image: dnfwlxo11/daein-lyrics-logstash:1.2.0
          name: daein-logstash
          ports:
            - containerPort: 5001
          resources: {}
          volumeMounts:
            - mountPath: /usr/share/logstash/config/logstash.yml
              name: daein-logstash-hostpath0
            - mountPath: /usr/share/logstash/pipeline/logstash.conf
              name: daein-logstash-hostpath1
            - mountPath: /opt/logstash/vendor/jar/jdbc/mariadb-java-client-2.7.5.jar
              name: daein-logstash-hostpath2
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /Users/daein/workspace-private/lyrics-player-k8s/lyrics-player/kompose/volumes/logstash/config/logstash.yml
          name: daein-logstash-hostpath0
        - hostPath:
            path: /Users/daein/workspace-private/lyrics-player-k8s/lyrics-player/kompose/volumes/logstash/config/logstash.conf
          name: daein-logstash-hostpath1
        - hostPath:
            path: /Users/daein/workspace-private/lyrics-player-k8s/lyrics-player/kompose/volumes/logstash/driver/mariadb-java-client-2.7.5.jar
          name: daein-logstash-hostpath2
status: {}
