apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: daein-nodejs
  name: daein-nodejs
spec:
  type: NodePort
  ports:
    - name: 'nodejs'
      nodePort: 30000
      port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    io.kompose.service: daein-nodejs
status:
  loadBalancer: {}
