# -*- mode: ruby -*-
# vi: set ft=ruby :

# 2는 실행할때 작동하는 API 버전
Vagrant.configure("2") do |config|
    # vitrualbox에서 보이는 가상머신
    # 설정 명을 daein으로 정의
    config.vm.define "daein" do |cfg|
      # 해당 vm box를 지정
      cfg.vm.box = "centos/7"
      # vagrant의 제공자가 virtualbox라고 명시
      cfg.vm.provider "virtualbox" do |vb|
        vb.name = "daein_admin"
        vb.cpus = 2
        vb.memory = 3072
        # 설정 커스터마이즈
        vb.customize ["modifyvm", :id, "--groups", "/daein_vms"]
      end
  
      # 가상머신에 대한 설정
      # 호스트 이름을 daein으로 설정
      cfg.vm.host_name = "daein"
      # 네트워크를 private 설정, IP 설정
      cfg.vm.network "private_network", ip: "192.168.1.10"
      # 통신 포트포워딩, auto_correct는 중복시 포트 자동 변경 옵션
      cfg.vm.network "forwarded_port", guest: 22, host: 60000, auto_correct: true, id: "ssh"
      # 호스트와 가상머신과 볼륨 설정, disabled는 동기화 비활성화 옵션
      cfg.vm.synced_folder "./data", "/vagrant", disabled: true
      # 호스트의 파일을 가상버신 내부에서 호출하여 실행
      cfg.vm.provision "shell", path: "init_package.sh"
    end
  end