# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    N = 3 # max number of worker nodes
    Ver = '1.18.4' # Kubernetes Version to install

    #=============#
    # Master Node #
    #=============#
    config.vm.define "daein-k8s" do |cfg|
        cfg.vm.box = "centos/7"
        cfg.vm.provider "virtualbox" do |vb|
        vb.name = "daein-k8s"
        vb.cpus = 2
        vb.memory = 3072
        vb.customize ["modifyvm", :id, "--groups", "/k8s-SgMST-1.13.1(github_SysNet4Admin)"]
        end

        cfg.vm.host_name = "daein-k8s"
        cfg.vm.network "private_network", ip: "192.168.1.10"
        cfg.vm.network "forwarded_port", guest: 22, host: 60000, auto_correct: true, id: "ssh"
        cfg.vm.synced_folder "../data", "/vagrant", disabled: true 
        cfg.vm.provision "shell", path: "config.sh", args: N
        cfg.vm.provision "shell", path: "init_package.sh", args: [ Ver, "Main" ]
        cfg.vm.provision "shell", path: "master_node.sh"
    end

    #==============#
    # Worker Nodes #
    #==============#
    (1..N).each do |i|
        config.vm.define "daein-k8s-#{i}" do |cfg|

        cfg.vm.box = "centos/7"
        cfg.vm.provider "virtualbox" do |vb|
            vb.name = "daein-k8s-#{i}"
            vb.cpus = 1
            vb.memory = 1024
            vb.customize ["modifyvm", :id, "--groups", "/daein-k8s"]
        end

        cfg.vm.host_name = "daein-k8s-#{i}"
        cfg.vm.network "private_network", ip: "192.168.1.10#{i}"
        cfg.vm.network "forwarded_port", guest: 22, host: "6000#{i}", auto_correct: true, id: "ssh"
        cfg.vm.synced_folder "./data", "/vagrant", disabled: true
        cfg.vm.provision "shell", path: "config.sh", args: N
        cfg.vm.provision "shell", path: "init_package.sh", args: Ver
        cfg.vm.provision "shell", path: "work_nodes.sh"

        end
    end

end