# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "daein" do |cfg|
    cfg.vm.box = "centos/7"
    cfg.vm.provider "virtualbox" do |vb|
      vb.name = "daein-machine"
      vb.cpus = 2
      vb.memory = 2048
      vb.customize ["modifyvm", :id, "--groups", "/daein_vms"]
    end

    cfg.vm.host_name = "daein"
    cfg.vm.network "private_network", ip: "192.168.1.100"
    cfg.vm.network "forwarded_port", guest: 22, host: 60000, auto_correct: true, id: "ssh"
    cfg.vm.synced_folder "./data", "/vagrant", disabled: true
    cfg.vm.provision "shell", path: "init_package.sh"
    cfg.vm.provision "file", source: "ping_test.sh", destination: "ping_test.sh"
    cfg.vm.provision "shell", path: "config.sh"
  end
  #==================#
  # additional Nodes #
  #==================#
  (1..3).each do |i|
    config.vm.define "daein-#{i}" do |cfg|
      cfg.vm.box = "centos/7"
      cfg.vm.provider "virtualbox" do |vb|
        vb.name = "daein-machine-#{i}"
        vb.cpus = 1
        vb.memory = 1024
        vb.customize ["modifyvm", :id, "--groups", "/daein_vms"]
      end

      cfg.vm.host_name = "daein-#{i}"
      cfg.vm.network "private_network", ip: "192.168.1.10#{i}"
      cfg.vm.network "forwarded_port", guest: 22, host: "6000#{i}", auto_correct: true, id: "ssh"
      cfg.vm.synced_folder "./data", "/vagrant", disabled: true
      cfg.vm.provision "shell", path: "init_package.sh"
    end
  end
end
